{"name": "test_create_user_with_list_wrong_param", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 500\nassert 500 == 400", "trace": "self = <test_api.TestWrongParameters object at 0x0000015C50B622B0>, api_con = <api_connector.ApiConnector object at 0x0000015C5142D4C0>, params = <class 'api_connector.ParamsReq'>\n\n    @allure.feature(\"Creates list of users /user/createWithList\")\n    @allure.story('Создаем пользователей списком с некорректным id')\n    @pytest.mark.create_user_with_list\n    def test_create_user_with_list_wrong_param(self, api_con, params):\n        \"\"\"created user with list params wrong-id\"\"\"\n        z_id = 'test'\n        with allure.step(f\"Создаем пользователя с id={z_id}\"):\n            rez = api_con.create_user_with_list(params(id=z_id))\n        with allure.step(f\"Запрос отправлен, проверяем код ответа {rez[0]} == 400\"):\n>           assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\nE           AssertionError: Неверный код ответа, получен 500\nE           assert 500 == 400\n\ntest_api.py:231: AssertionError"}, "description": "created user with list params wrong-id", "steps": [{"name": "Создаем пользователя с id=test", "status": "passed", "steps": [{"name": "POST request to: https://petstore.swagger.io/v2/user/createWithList", "status": "passed", "start": 1661536230172, "stop": 1661536230172}], "start": 1661536229496, "stop": 1661536230172}, {"name": "Запрос отправлен, проверяем код ответа 500 == 400", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 500\nassert 500 == 400\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\tz_api\\test_api.py\", line 231, in test_create_user_with_list_wrong_param\n    assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\n"}, "start": 1661536230172, "stop": 1661536230173}], "start": 1661536229495, "stop": 1661536230174, "uuid": "7e3890f6-97b7-4c54-a121-f8716854debc", "historyId": "57977be5aa23d9fbd066efdb09285bbd", "testCaseId": "4bc9659340e0c48cc64c9e2b005b9680", "fullName": "test_api.TestWrongParameters#test_create_user_with_list_wrong_param", "labels": [{"name": "story", "value": "Создаем пользователей списком с некорректным id"}, {"name": "feature", "value": "Creates list of users /user/createWithList"}, {"name": "tag", "value": "create_user_with_list"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestWrongParameters"}, {"name": "host", "value": "DESKTOP-TEN2FQ3"}, {"name": "thread", "value": "10216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}