{"name": "test_login_user_without_password", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: Неверный код ответа, получен 200\nassert 200 == 400", "trace": "self = <test_api.TestNoParam object at 0x00000256CC28B790>, api_con = <api_connector.ApiConnector object at 0x00000256CC2EBA00>\n\n    @allure.feature(\"Login user into the system  /user/login\")\n    @allure.story('Выполняем вход пользователя без указания обязательного параметра password')\n    @pytest.mark.login_user\n    @pytest.mark.xfail\n    def test_login_user_without_password(self, api_con):\n        \"\"\"logged user without password\"\"\"\n        rez = api_con.login_user(name='test')\n        with allure.step(\"Запрос отправлен, проверяем код ответа\"):\n>           assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\nE           AssertionError: Неверный код ответа, получен 200\nE           assert 200 == 400\n\ntest_api.py:72: AssertionError"}, "description": "logged user without password", "steps": [{"name": "GET request to: https://petstore.swagger.io/v2/user/login", "status": "passed", "start": 1661531995332, "stop": 1661531995332}, {"name": "Запрос отправлен, проверяем код ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 400\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\tz_api\\test_api.py\", line 72, in test_login_user_without_password\n    assert rez[0] == 400, f'Неверный код ответа, получен {rez[0]}'\n"}, "start": 1661531995332, "stop": 1661531995333}], "start": 1661531994712, "stop": 1661531995334, "uuid": "bcbf4f78-b66d-473b-b37f-5939220bb923", "historyId": "db220aca4d92294879a19825ba253c85", "testCaseId": "77ce176434bd91fd0aab706de08a966d", "fullName": "test_api.TestNoParam#test_login_user_without_password", "labels": [{"name": "feature", "value": "Login user into the system  /user/login"}, {"name": "story", "value": "Выполняем вход пользователя без указания обязательного параметра password"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "tag", "value": "login_user"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestNoParam"}, {"name": "host", "value": "DESKTOP-TEN2FQ3"}, {"name": "thread", "value": "16092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}