{"name": "test_update_by_wrong_name", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: Неверный код ответа, получен 200\nassert 200 == 404", "trace": "self = <test_api.TestWrongParameters object at 0x00000256CC29F040>, add_one_user = <api_connector.ApiConnector object at 0x00000256CC2EBF70>, params = <class 'api_connector.ParamsReq'>\n\n    @allure.feature(\"Updated user /user/{username}\")\n    @allure.story('Обновляем пользователя с некорректным username')\n    @pytest.mark.update_user\n    @pytest.mark.xfail\n    def test_update_by_wrong_name(self, add_one_user, params):\n        \"\"\"updated user by wrong name\"\"\"\n        rez = add_one_user.update_user('test_user', params(id=100, email='test@test.ru'))\n        with allure.step(\"Запрос отправлен, проверяем код ответа\"):\n>           assert rez[0] == 404, f'Неверный код ответа, получен {rez[0]}'\nE           AssertionError: Неверный код ответа, получен 200\nE           assert 200 == 404\n\ntest_api.py:233: AssertionError"}, "description": "updated user by wrong name", "steps": [{"name": "DELETE request to: https://petstore.swagger.io/v2/user/test_user", "status": "passed", "start": 1661532014322, "stop": 1661532014322}, {"name": "Запрос отправлен, проверяем код ответа", "status": "failed", "statusDetails": {"message": "AssertionError: Неверный код ответа, получен 200\nassert 200 == 404\n", "trace": "  File \"C:\\Users\\User\\PycharmProjects\\tz_api\\test_api.py\", line 233, in test_update_by_wrong_name\n    assert rez[0] == 404, f'Неверный код ответа, получен {rez[0]}'\n"}, "start": 1661532014322, "stop": 1661532014323}], "start": 1661532013646, "stop": 1661532014324, "uuid": "d0e4d577-3601-4ac4-9f6e-7918b9f3753a", "historyId": "abc83da211e5765ee1e6ddeebc6fa82a", "testCaseId": "a1d70af3f78850bcee4f422d425912cc", "fullName": "test_api.TestWrongParameters#test_update_by_wrong_name", "labels": [{"name": "feature", "value": "Updated user /user/{username}"}, {"name": "story", "value": "Обновляем пользователя с некорректным username"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "tag", "value": "update_user"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestWrongParameters"}, {"name": "host", "value": "DESKTOP-TEN2FQ3"}, {"name": "thread", "value": "16092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_api"}]}